# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Editor Review Tones' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Editor Review Tones
  pod 'SwiftLint'
  
  target 'Editor Review TonesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Editor Review TonesUITests' do
    # Pods for testing
  end

end
